/**
 * Copyright (c) 2011, The University of Southampton and the individual contributors.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * * 	Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * *	Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * *	Neither the name of the University of Southampton nor the names of its
 * contributors may be used to endorse or promote products derived from this
 * software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.github.sarxos.webcam.ds.buildin.natives

import org.bridj.Pointer
import org.bridj.ann.Field
import org.bridj.ann.Library
import org.bridj.ann.Runtime
import org.bridj.cpp.CPPObject
import org.bridj.cpp.CPPRuntime

/**
 * *native declaration : line 1*<br></br>
 * This file was autogenerated by [JNAerator](http://jnaerator.googlecode.com/),<br></br>
 * a tool written by [Olivier Chafik](http://ochafik.free.fr/) that
 * [uses a
 * few opensource projects.](http://code.google.com/p/jnaerator/wiki/CreditsAndLicense).<br></br>
 * For help, please visit [NativeLibs4Java](http://nativelibs4java.googlecode.com/) or [BridJ](http://bridj.googlecode.com/) .
 */
@Library("OpenIMAJGrabber")
@Runtime(CPPRuntime::class)
class Device : CPPObject {
    constructor() : super() {}
    constructor(pointer: Pointer<out CPPObject>?) : super(pointer) {}

    // / C type : const char*
    @Field(0)
    protected fun name(): Pointer<Byte> {
        return io.getPointerField(this, 0)
    }

    // / C type : const char*
    @Field(0)
    protected fun name(name: Pointer<Byte>?): Device {
        io.setPointerField(this, 0, name)
        return this
    }

    // / C type : const char*
    @Field(1)
    protected fun identifier(): Pointer<Byte> {
        return io.getPointerField(this, 1)
    }

    // / C type : const char*
    @Field(1)
    protected fun identifier(identifier: Pointer<Byte>?): Device {
        io.setPointerField(this, 1, identifier)
        return this
    }

    protected val name: Pointer<Byte?>
        external get
    val nameStr: String
        get() = name.cString
    protected val identifier: Pointer<Byte?>
        external get
    val identifierStr: String
        get() = identifier.cString

    /*
	 * (non-Javadoc)
	 * @see org.bridj.NativeObject#equals(java.lang.Object)
	 */
    override fun equals(other: Any?): Boolean {
        return other.toString() == this.toString()
    }

    /*
	 * (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
    override fun hashCode(): Int {
        return this.toString().hashCode()
    }

    override fun toString(): String {
        return String.format("Device[%s]=\"%s\"", identifierStr, nameStr)
    }
}